[git_status]
conflicted = "="
ahead = "â‡¡${count} "
behind = "â‡£${count} "
diverged = "ðŸ‡Ã—${ahead_count} ðŸ¢Ã—${behind_count} "
untracked = "?${count} "
stashed = "*${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "Â»${count} "
deleted = "âœ˜${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[nodejs]
format = " "

[package]
format = " "

[character]

vicmd_symbol = "[N >](bold green)"
